trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core 6 SDK'
    inputs:
      packageType: sdk
      version: 6.0.x

  - task: AzureStaticWebApp@0
    inputs:
      app_location: "Client" # App source code path
      api_location: "Api" # Api source code path
      output_location: "wwwroot" # Built app content directory

    env:
      azure_static_web_apps_api_token: $(API_TOKEN)